### ISSUE TITLE
ImagePullBackOff errors when trying to deploy Spotfire Server 12.4.0

### ISSUE THREAD

**Issue by jtmulcahey** [TIBCOSoftware/spotfire-cloud-deployment-kit#13]
I have a local Kind Kubernetes cluster running with a registry on port 5001. This runs on an Ubuntu WSL2 instance. I want to deploy Spotfire Server in this K8s cluster.

I'm able to build and push the container images to that registry. But when I run the helm install command, I get some ImagePullBackOff errors. Here's the command I ran..

```
$ cd charts/spotfire-server/
$ helm install vanilla-tss-12-4-0 . \
    --set acceptEUA=true \
    --set global.spotfire.image.registry="127.0.0.1:5001" \
    --set global.spotfire.image.pullPolicy="Always" \
    --set database.bootstrap.databaseUrl="jdbc:postgresql://vanilla-tssdb-postgresql.default.svc.cluster.local/" \
    --set database.create-db.databaseUrl="jdbc:postgresql://vanilla-tssdb-postgresql.default.svc.cluster.local/" \
    --set database.create-db.adminUsername="postgres" \
    --set database.create-db.adminPassword="$POSTGRES_PASSWORD" \
    --set database.create-db.enabled=true \
    --set configuration.site.publicAddress="http://localhost"
```

Note that I already started the bitnami postgres instance as instructed, and obtained the password for the db admin user.

When I describe one of the pods that has the ImagePullBackOff error, I see..

` Warning  Failed     14s (x2 over 29s)  kubelet            Failed to pull image "127.0.0.1:5001/tibco/spotfire-config:12.4.0-1.4.0": rpc error: code = Unknown desc = failed to pull and unpack image "127.0.0.1:5001/tibco/spotfire-config:12.4.0-1.4.0": failed to resolve reference "127.0.0.1:5001/tibco/spotfire-config:12.4.0-1.4.0": failed to do request: Head "http://127.0.0.1:5001/v2/tibco/spotfire-config/manifests/12.4.0-1.4.0": dial tcp 127.0.0.1:5001: connect: connection refused`

I can successfully telnet to 127.0.0.1:5001.

When I look in ~/spotfire-cloud-deployment-kit-1.4.0/helm/charts/, I don't see spotfire-config.

I'm using the SF Server 12.4.0 installation files.

How do I fix this or at least troubleshoot further? Thanks.

**Comment by jtmulcahey** [comment]
Ah.. I see that the spotfire-config files are not part of version 1.4.0, but when I clone the current version, these files exist under spotfire-cloud-deployment-kit/containers/spotfire-config/. So I will try again with the current version.

**Comment by jtmulcahey** [comment]
hm.. well I tried the current version, but it still has the same problem. I must be missing a step with regards to spotfire-config.

**Comment by mjohanss-tibco** [comment]
You need to build the container images and then push them up to a container registry that is accessible by your Kubernetes cluster. By setting `--set global.spotfire.image.registry="127.0.0.1:5001"` you are telling the pods to get the images from the registry at 127.0.0.1:5001. First make sure that you have pushed all images to your registry, then if that's not the default location where your kubernetes installation looks for images you can supply `--set global.spotfire.image.registry="<YOUR IMAGE REGISTRY ADDRESS HERE>"`.

**Comment by jtmulcahey** [comment]
The issue was indeed due to an inability to connect to the local registry. Here's what I did to get it up and running in minikube:

```
$ minikube start --cpus 4 --memory 4096
$ minikube addons enable registry
$ kubectl port-forward --namespace kube-system service/registry 5000:80
```

Then in a separate terminal:

```
$ helm repo add bitnami https://charts.bitnami.com/bitnami
$ helm install vanilla-tssdb bitnami/postgresql
$ export POSTGRES_PASSWORD=$(kubectl get secret --namespace default vanilla-tssdb-postgresql -o jsonpath="{.data.postgres-password}" | base64 --decode)
$ make build
$ make REGISTRY=localhost:5000 push
$ helm install vanilla-tss-12-4-0 . \
    --set acceptEUA=true \
    --set global.spotfire.image.registry="localhost:5000" \
    --set global.spotfire.image.pullPolicy="Always" \
    --set database.bootstrap.databaseUrl="jdbc:postgresql://vanilla-tssdb-postgresql.default.svc.cluster.local/" \
    --set database.create-db.databaseUrl="jdbc:postgresql://vanilla-tssdb-postgresql.default.svc.cluster.local/" \
    --set database.create-db.adminUsername="postgres" \
    --set database.create-db.adminPassword="$POSTGRES_PASSWORD" \
    --set database.create-db.enabled=true \
    --set configuration.site.publicAddress="http://localhost"
```
Thanks.
