### ISSUE TITLE
spotfire-webplayer permission denied error

### ISSUE THREAD

**Issue by devuser35** [TIBCOSoftware/spotfire-cloud-deployment-kit#15]
In the Dockerfile containers/spotfire-webplayer/Dockerfile there is

```
RUN /opt/tibco/tsnm/scripts/install-service.sh \
    --capability="${TSNM_CAPABILITY}" \
    --framework=NETCORE \
    --directory=/tmp/tsnm-packages \
    --directory-pattern=*.{sdn,spk}
```

When I run make for this I get 

 ```
=> [extract 5/6] ADD --chown=spotfire:spotfire build/*.sdn build/*.spk /tmp/tsnm-packages/                                                                   1.5s
 => ERROR [extract 6/6] RUN /opt/tibco/tsnm/scripts/install-service.sh     --capability="WEB_PLAYER"     --framework=NETCORE     --directory=/tmp/tsnm-packa  0.2s
------
 > [extract 6/6] RUN /opt/tibco/tsnm/scripts/install-service.sh     --capability="WEB_PLAYER"     --framework=NETCORE     --directory=/tmp/tsnm-packages     --directory-pattern=*.{sdn,spk}:
#0 0.202 /bin/sh: 1: /opt/tibco/tsnm/scripts/install-service.sh: Permission denied
```
------

Quick workaround for me was :

```
# Note: multiple --file arguments can be used instead of --directory and --directory-pattern to only use specific files
RUN chmod 755 /opt/tibco/tsnm/scripts/install-service.sh
RUN /opt/tibco/tsnm/scripts/install-service.sh \
```

**Comment by mjohanss-tibco** [comment]
Are you building from a file system that doesn't does not have the executable bit on files for example if you check out the code on a windows machine, then build from WSL2 but the files reside under /mnt/c/? I think this could be the problem in your case.

**Comment by mjohanss-tibco** [comment]
Closing the bug since more information is required. It's possible that the issue has been fixed in the latest release also. If this issue happens again, make sure that the files has been checked out with the right permissions (same as in git) and if the issues persists file a new bug report.
