### ISSUE TITLE
Spotfire 12.4.0 is not available anymore

### ISSUE THREAD

**Issue by rodrigoeiras** [TIBCOSoftware/spotfire-cloud-deployment-kit#16]
Need a workaround to pass the version when building.
Actual version is 12.5.0

**Comment by rodrigoeiras** [comment]
I saw versions.mk file listing Spotfire versions. Will try modify and run again.

Edit:
Worked. My versions.mk content below:


CLOUD_DEPLOYMENT_KIT_VERSION=1.4.0
SPOTFIRE_DEPLOYMENT_VERSION=12.5.0
SPOTFIRE_NETCORE_LANGUAGEPACKS_VERSION=12.5.0
SPOTFIRE_NETCORE_VERSION=12.5.0
SPOTFIRE_NODEMANAGER_VERSION=12.5.0
SPOTFIRE_PYTHONSERVICE_VERSION=1.16.0
SPOTFIRE_SERVER_VERSION=12.5.0
SPOTFIRE_TERRSERVICE_VERSION=1.16.0

**Comment by mjohanss-tibco** [comment]
[Release 1.5.0 ](https://github.com/TIBCOSoftware/spotfire-cloud-deployment-kit/releases/tag/v1.5.0) supports the following application versions. I recommend using this release of the CDK over modifying version.mk for an older CDK release.

- TIBCO Spotfire Server 12.5.0
- TIBCO Spotfire Web Player 12.5.0
- TIBCO Spotfire Automation Services 12.5.0
- TIBCO Enterprise Runtime for R - Server Edition 1.16.0
- TIBCO Spotfire Service for Python 1.16.0
- TIBCO Spotfire Service for R 1.16.0

@rodrigoeiras Thanks for filing the report. I will be closing this issue now.
