### ISSUE TITLE
Required installation files are not listed

### ISSUE THREAD

**Issue by pmckinnis** [TIBCOSoftware/spotfire-cloud-deployment-kit#18]
The containers/Readme needs to be more clear regarding the files needed for building.  In the "Build the images" section, Step 1 needs some editing.   Step 1 first states that the files listed in "Prerequisites" should be copied (no files are listed in Prerequisites).  The second line states to "See build-files.mk for a list of files...."    These two lines need to be edited to make it more clear where to find the list of files needed.

Maybe something like "The files listed in build-files.mk need to be copied into the <this-repo>/containers/downloads directory.  One can also see the list of files needed by running make xxxxxxx"

Thanks,
Peter

**Comment by mjohanss-tibco** [comment]
Thanks for the report. 

For anyone wondering these are the files that should be placed under containers/downloads before the container images can be built:

- Spotfire.Dxp.PythonServiceLinux.sdn
- Spotfire.Dxp.TerrServiceLinux.sdn
- Spotfire.Dxp.sdn
- tsnm-12.5.0.x86_64.tar.gz
- Spotfire.Dxp.RServiceLinux.sdn
- Spotfire.Dxp.netcore-linux.sdn
- TIB_sfire_server_12.5.0_languagepack-multi.zip
- tss-12.5.0.x86_64.tar.gz

**Comment by mjohanss-tibco** [comment]
This has been addressed in the latest. See build-files.mk for a list of files needed to build the images or run `make downloads-list` (in containers/) to list them.
