### ISSUE TITLE
Config Lab Not Supporting Some Commands That Required Restart

### ISSUE THREAD

**Issue by alexandrev** [TIBCOSoftware/spotfire-cloud-deployment-kit#3]
This is a situation that is making the solution not as cloud-native as it should be. If I want to run some configuration commands such as changing the User Authentication system to LDAP for example, that requires a restart of the Spotfire Server. 

As the currently Job that is doing the config and the pod for spotfire-server is launched at the same time, you are forced to restart the pod for spotfire-server manually to load the new configuration. This is not a very cloud-native approach and we should find a better way to do so.

**Comment by mjohanss-tibco** [comment]
The intention is that you should not be required to manually restart the servers when making configuration changes. When the spotfire server detects configuration changes it will shut down when using the default Kubernetes configuration file:

`set-config-prop --name=lifecycle.changes-monitoring.configuration-change-action --value=GRACEFUL_SHUTDOWN --configuration="${CONFIGURATION_FILE}" --bootstrap-config="${BOOTSTRAP_FILE}"
`

See 
https://github.com/TIBCOSoftware/spotfire-cloud-deployment-kit/blob/main/helm/charts/spotfire-server/config-job-scripts/default-kubernetes-config.txt#L22

The new configuration will be active after a while when the server starts up again. Is this now working for you?

**Comment by alexandrev** [comment]
Thanks @mjohanss-tibco I was able to validate what you commented. Spotfire-Server is restarted automatically. Sorry for bring up a topic that was not 100% accurate. Closing the issue.
