### ISSUE TITLE
ER: Remove Credentials as Environment Variables

### ISSUE THREAD

**Issue by alexandrev** [TIBCOSoftware/spotfire-cloud-deployment-kit#6]
Currently, there are some credentials that are managed as Secrets but loaded as Environment Variables in the containers. 

This is considered as not best practice for some customers: 

https://blog.nillsf.com/index.php/2020/02/24/dont-use-environment-variables-in-kubernetes-to-consume-secrets/

Can this be handled as an ER?

**Comment by mdiez-tibco** [comment]
Hi @alexandrev,
Indeed this is something we are already looking into.
Thanks!

**Comment by mdiez-tibco** [comment]
Yes. There are certainly some alternatives to using environment variables. 
However, they might add quite a bit of complexity to the deployment. And many of them depend on integration with other tooling.

So far, we have not seen any indication of a real customer need/query for this improvement.

The purpose of the CDK is to provide generic recipes that would work for most of the scenarios for our customers.
Trying to provide a solution for this in a not generic way will not be helpful for most of them. 
Note that it is always possible to modify these recipes or propose a solution that would be useful for specific scenarios.
Therefore, I'll close this issue for the time being.
